version: '3'
services:
  back:
    image: "equiperocket/poc-back:latest"
    ports:
      - '8080:8080'
      - '5001:5000'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://poc.cy57hfox1fy1.us-east-1.rds.amazonaws.com:3306/poc?useUnicode=true&characterEncoding=utf8&useSSL=true&allowPublicKeyRetrieval=true
      - ARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5000 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
      - DB_PASSWORD=kASe1QkIm5xQUZMF7cXo5000
      - DB_USER=admin
  https-portal:
    image: steveltn/https-portal
    ports:
      - '80:80'
      - '443:443'
    links:
      - back
    restart: always
    environment:
      #      DOMAINS: 'teste.local -> http://back:8080'
      #      STAGE: local
      DOMAINS: 'https://certvet-front.us-east-1.elasticbeanstalk.com -> http://back:8080/'
#       STAGE: 'production'
#       FORCE_RENEW: 'true'